version: 2.1
executors:
  my-executor:
    


commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: npm install

jobs:
  build:
    docker:
      - image: circleci/node:lts

    working_directory: ~/project/src

    steps:
      - checkout:
          path: ~/project
      - install_deps
      - run:
          name: run unit test
          command: npm run test-unit

workflows:
  version: 2
  build-test-package:
    jobs:
      - build