version: 2.1

commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: npm install

jobs:
  build:
    docker:
      - image: circleci/node:lts

    working_directory: ~/project/src

    steps:
      - checkout:
          path: ~/project
      - install_deps
      
      - run:
          name: run linting
          command: npm run test-lint

      - run:
          name: run unit test
          command: npm run test-unit

      - store_test_results:
          path: test_outputs

      - run:
          name: validate code coverage
          command: bash <(curl -s https://codecov.io/bash) 

  integration-tests:
    docker:
      - image: circleci/node:lts
      - image: circleci/postgres:9.6.2-alpine
    steps:
      - checkout
      - install_deps
      - run:
          name: Run integration tests
          command: npm run test-integration


workflows:
  version: 2
  build-test-package:
    jobs:
      - build
      - integration-tests:
         requires:
           - build