version: 2.1

commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: npm install

jobs:
  build:
    docker:
      - image: circleci/node:lts

    working_directory: ~/project/src

    steps:
      - checkout:
          path: ~/project
      - install_deps
      
      - run:
          name: run linting
          command: npm run test-lint

      - run:
          name: run unit test
          command: npm run test-unit

      - store_test_results:
          path: test_outputs

      - run:
          name: validate code coverage
          command: bash <(curl -s https://codecov.io/bash)

  integration-tests:
    docker:
      - image: circleci/node:lts
      - image: circleci/postgres:latest
        environment:
          POSTGRES_DB: servian
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
    working_directory: ~/project/src
    steps:
      - checkout:
          path: ~/project
      - install_deps
      - run: 
          name: wait for database
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run integration tests
          command: npm run test-integration

  e2e-test:
    docker:
      - image: qawolf/playwright-ci:v0.9.0
      - image: circleci/node:lts-browsers
      - image: circleci/postgres:latest
        environment:
          POSTGRES_DB: servian
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
    working_directory: ~/project/src
    steps:
      - checkout:
          path: ~/project

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          command: |
            npm run test-e2e
          environment:
            # configure tests with environment variables
            QAW_ARTIFACT_PATH: /tmp/artifacts
            QAW_HEADLESS: true
            POSTGRES_DB: servian
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
      - store_artifacts:
          path: /tmp/artifacts


workflows:
  version: 2
  build-test-package:
    jobs:
      - build
      - integration-tests:
          requires:
           - build
      - e2e-test:
          requires:
            - build
            - integration-tests