version: 2.1

commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: npm install

jobs:
  build:
    docker:
      - image: circleci/node:lts

    working_directory: ~/project/src

    steps:
      - checkout:
          path: ~/project
      - install_deps
      - run:
          name: run unit test
          command: npm run test-unit
      - run:
          name: validate code coverage
          command: bash <(curl -s https://codecov.io/bash) 


workflows:
  version: 2
  build-test-package:
    jobs:
      - build