version: 2.1

commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: npm install

jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers

    working_directory: ~/project/src

    steps:
      - checkout:
          path: ~/project
      - install_deps
      
      - run:
          name: run linting
          command: npm run test-lint

      - run:
          name: run unit test
          command: npm run test-unit

      - store_test_results:
          path: test_outputs

      - run:
          name: validate code coverage
          command: bash <(curl -s https://codecov.io/bash)

  integration-tests:
    docker:
      - image: circleci/node:lts-browsers
      - image: circleci/postgres:latest
        environment:
          POSTGRES_DB: servian
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
    working_directory: ~/project/src
    steps:
      - checkout:
          path: ~/project
      - install_deps
      - run: 
          name: wait for database
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run integration tests
          command: npm run test-integration

  e2e-test:
    docker:
      - image: circleci/node:lts-browsers
        environment:
          QAW_HEADLESS: true
      - image: circleci/postgres:latest
        environment:
          POSTGRES_DB: servian
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
      - image: qawolf/playwright-ci:v0.9.0
        environment:
    working_directory: ~/project/src
    steps:
      - checkout:
          path: ~/project
      - install_deps

      - run: 
          name: wait for database
          command: dockerize -wait tcp://localhost:5432 -timeout 1m         
          background: true 
      - run:
          name: start background server
          command: |
            npm run start & 
            npx wait-on http://localhost:3000
          environment:
            POSTGRES_DB: servian
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
      - run:
          command: |
            npm run test-e2e
          environment:
            # configure tests with environment variables
            QAW_ARTIFACT_PATH: /tmp/artifacts
            QAW_HEADLESS: true
      - store_artifacts:
          path: /tmp/artifacts


workflows:
  version: 2
  build-test-package:
    jobs:
      - build
      - integration-tests:
          requires:
           - build
      - e2e-test:
          requires:
            - build