version: "3"
services:
  db:
    container_name:  db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: servian
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"